apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nodejs-ialxrxas-gitops
  description: This is GitOps manifest for nodejs-ialxrxas   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=nodejs-ialxrxas
    backstage.io/kubernetes-id: nodejs-ialxrxas 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: nodejs-ialxrxas
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nodejs-ialxrxas
